INSERT INTO USER (USERNAME, PASSWORD) VALUES ('amit', '$2a$12$F5PNCr/VyfZrUuRCh/VRWOLfCqXfj53lq21.7B2lUms53wXifLnGO');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('joe', '$2a$12$tYyxfgjdAo8R8NA3jExXlOdIyECPQRAWcIrYLwWVoVHkRGg4pFB2C');


